backend:
  name: git-gateway
  branch: master

# when using the default proxy server port
local_backend: true

media_folder: static/blog_assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: slug, label: Slug, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: thumbnail, label: Thumbnail, widget: image }
