name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install autoreconf
        run: sudo apt-get install autoconf automake pkg-config libgtk-3-dev dh-autoreconf

      - name: autoreconf --version
        run: autoreconf --version

      - name: Yarn install
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Yarn build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build:prod # will run `yarn build:prod` command

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
